### ISSUE TITLE
Use bevy's Focus resource instead of ActiveEditor

### ISSUE THREAD

**Issue by Dimchikkk** [StaffEngineer/bevy_cosmic_edit#32]
Instead of ActiveEditor resource let's use `Focus` component (or any other better named marker component).

**Comment by Dimchikkk** [comment]
@bytemunch what do you think about it?

**Comment by bytemunch** [comment]
yeah was thinking about this when looking at the focus policy UI stuff, could replace the `ActiveEditor` resource, but then we may lose the guaranteed single active element, which may or may not be desirable. Not much code to ensure we remove the previous tag before adding a tag to the next editor.

For a11y we should probably use this https://docs.rs/bevy/latest/bevy/a11y/struct.Focus.html which is a resource that takes an `Option<Entity>>`, may be the way to go.

I much prefer querying with tag elements, but the definite singular entity from a resource seems to be more advantageous.

Just means a lot of
```rs
fn system_name(query: Query<&ComponentName>, focused_resource: Res<Focus>) {
  if let Some(entity) = focused_resource.0 {
    if Ok(component) = query.get(entity) {
      do_thing(component);
    }
  }
}
```

**Comment by Dimchikkk** [comment]
Yeah, it has pros&cons, thanks for sharing `Focus` link from a11y, didn't know about that... let me think more about it.

**Comment by Dimchikkk** [comment]
Giving it another thought I think you are right about that:

> For a11y we should probably use this https://docs.rs/bevy/latest/bevy/a11y/struct.Focus.html which is a resource that takes an Option<Entity>>, may be the way to go.

**Comment by Dimchikkk** [comment]
Oh `pub struct Focus(_);` has private constructor

**Comment by bytemunch** [comment]
Might be a bigger job than expected, a11y seems a little complex, there's a fair bit to learn. From a quick (but closer than yesterday) look it seems like the widgets will need some accesskit components, and then they send `Action`s to an `ActionHandler` when requesting or ceding focus?

I think instead of a simple resource change this will require some finesse, doesn't seem like a11y can be half-implemented. It does feel important for a text input though. Perhaps this issue should be "implement bevy::a11y"?

**Comment by Dimchikkk** [comment]
I am going to rename ActiveEditor to Focus and close the issue, we can come back to a11y a bit later I think.
