### ISSUE TITLE
Starting without a focused input holds a stuck cursor on all placeholders

### ISSUE THREAD

**Issue by bytemunch** [StaffEngineer/bevy_cosmic_edit#82]

**Comment by carlquer** [comment]
(Windows 11)

I think I hit this one now, kind of. I was trying to use bevy_cosmic_edit in my application and was very confused because I only got a white box with the border on my textboxes (even if I set the background/fillcolor).... until I noticed that the examples has a Focus resource.

When I added the `change_active_editor_ui` system from the examples to set Focus to an editor when it is clicked, everything works. The text and background will be rendered (after receiving focus).

The same is true if you edit for example the `font_per_widget` example and comment out the `commands.insert_resource(Focus(id));` at line 258, then you get a white window until you click one of the two editors.

**Comment by bytemunch** [comment]
Yeah pretty sure I need to set the initial redraw state to true and this
should fix it, maybe force a redraw every X seconds just to be sure. Will
try make time for it this evening :)
